[versions]
junit = "5.12.2"
paper = "1.21-R0.1-SNAPSHOT"
snakeyaml = "2.4"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
